server {

    listen 80;

    server_name rajacirengbekasi.web.id www.rajacirengbekasi.web.id;


    # untuk verifikasi certbot

    location /.well-known/acme-challenge/ {

        root /var/www/certbot;

    }


    # redirect HTTP ke HTTPS

    # location / {

    #     return 301 https://$host$request_uri;

    # }

    #TEMPORARY
      location / {
        return 200 "NGINX OK";
    }

}

server {

    listen 443 ssl;


    server_name rajacirengbekasi.web.id www.rajacirengbekasi.web.id;



    ssl_certificate
    /etc/letsencrypt/live/rajacirengbekasi.web.id/fullchain.pem;


    ssl_certificate_key
    /etc/letsencrypt/live/rajacirengbekasi.web.id/privkey.pem;




    # FRONTEND

    location / {


        proxy_pass http://frontend:80;


    }




    # BACKEND API

    location /api/ {


        proxy_pass http://backend:5000;



        proxy_set_header Host $host;


        proxy_set_header X-Real-IP $remote_addr;


    }

}